[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "flashcards"
version = "0.1.0"
description = "Flashcards GUI application"
authors = [
    { name="Your Name", email="you@example.com" }
]
requires-python = ">=3.10"
dependencies = []

[tool.setuptools.packages.find]
where = ["src"]

[tool.black]
line-length = 88
target-version = ["py311"]
skip-string-normalization = false

[tool.isort]
profile = "black"
line_length = 88
multi_line_output = 3
include_trailing_comma = true
use_parentheses = true
ensure_newline_before_comments = true
lines_after_imports = 2
known_first_party = ["domain", "application", "infrastructure", "presentation", "cross_cutting", "plugins"]
src_paths = ["src"]
combine_as_imports = true
import_heading_stdlib = "Standard library imports"
import_heading_thirdparty = "Third party imports"
import_heading_firstparty = "Local application imports"

